### ISSUE TITLE
Version font-awesome

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/tiriad#1]
La version actuelle utilisé est la 4.7.0, il faudrait migrer vers la dernière version

**Comment by Gaetanbrl** [comment]
Dernière version [npm ](https://www.npmjs.com/package/font-awesome): 4.7.0
Dernière version [bootstrapCDN](https://www.bootstrapcdn.com/) : 4.3.1

Utilisation [CDN Font Awesome](https://fontawesome.com/start) pour passage en v5.8.
