### ISSUE TITLE
Import de fichier geojson - sans partie serveur

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/tiriad#3]
**En tant que** utilisateur

**Je veux que pouvoir** ajouter des données en faisant un glisser déposé sur la carte d'un fichier geojson

**Afin de** voir les entitées et pouvoir cliquer sur chacune pour voir les attributs

Le nom de la couche doit correspondre au nom du fichier sans extensions, si la couche existe déjà elle doit être remplacée par la nouvelle couche

**Comment by Gaetanbrl** [comment]
[ddv-viewer/dev]
 
Import possible avec visualisation du nom de la couche selon l'attribut "name" contenu dans le JSON. 
A modifier pour prendre ne compte le nom du fichier sans l'extension.

Un style cluster est ajouté actuellement par défaut mais n'importe quel style est paramétrable.

Les attributs sont cliquables comme défini pour les autres couches à condition que la couche importée détienne les attributs utilisées dans la popup d'affichage des résultats.

**Comment by Gaetanbrl** [comment]
[ddv-viewer/dev]
Evolution faite : La couche importée dont le fichier a le même nom qu'une couche présente la remplace.
